#!/usr/bin/env bash
# Generates the Solidity verifier contracts (docs/methodology.md, Fase 1) from
# the verification keys produced by scripts/prove-all.sh, renaming the
# generated `HonkVerifier` contract per variant so all four coexist in one
# Foundry project. Also regenerates the proof fixtures consumed by the Foundry
# tests as hex constants, keeping tests free of filesystem access.
set -euo pipefail

cd "$(dirname "$0")/.."

command -v bb >/dev/null 2>&1 || { echo "error: bb not found in PATH" >&2; exit 1; }

variants=(field u8 u32 u64)
pascal() {
  case "$1" in
    field) echo "RangeProofField" ;;
    u8)    echo "RangeProofU8" ;;
    u32)   echo "RangeProofU32" ;;
    u64)   echo "RangeProofU64" ;;
  esac
}

fixtures="contracts/test/ProofFixtures.sol"
cat > "$fixtures" <<'EOF'
// SPDX-License-Identifier: MIT
pragma solidity >=0.8.21;

// Generated by scripts/generate-verifiers.sh from results/proofs/. Do not edit.
library ProofFixtures {
EOF

for v in "${variants[@]}"; do
  pkg="range_proof_$v"
  name="$(pascal "$v")Verifier"
  vk="results/proofs/$pkg/vk"
  [ -f "$vk" ] || { echo "error: $vk missing; run scripts/prove-all.sh first" >&2; exit 1; }

  bb write_solidity_verifier -k "$vk" -o "contracts/src/$name.sol" >/dev/null
  sed -i "s/^contract HonkVerifier is/contract $name is/" "contracts/src/$name.sol"
  echo "generated contracts/src/$name.sol"

  proof_hex=$(xxd -p -c 0 "results/proofs/$pkg/proof")
  pub_hex=$(xxd -p -c 0 "results/proofs/$pkg/public_inputs")
  n_inputs=$(( ${#pub_hex} / 64 ))
  {
    echo "    function $(pascal "$v" | sed 's/RangeProof//' | tr 'A-Z' 'a-z')Proof() internal pure returns (bytes memory, bytes32[] memory) {"
    echo "        bytes memory proof = hex\"$proof_hex\";"
    echo "        bytes32[] memory publicInputs = new bytes32[]($n_inputs);"
    i=0
    while [ $((i * 64)) -lt ${#pub_hex} ]; do
      echo "        publicInputs[$i] = bytes32(hex\"${pub_hex:$((i * 64)):64}\");"
      i=$((i + 1))
    done
    echo "        return (proof, publicInputs);"
    echo "    }"
  } >> "$fixtures"
done

echo "}" >> "$fixtures"
echo "generated $fixtures"
